version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks: 
      - mission-5
    
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    networks: 
      - mission-5
    stdin_open: true
    tty: true
    depends_on:
      - backend
    
networks: 
  mission-5: 
     driver: bridge